### ISSUE TITLE
online zoo v5

### ISSUE THREAD

**Issue by kubasovp** [IgorAblyak/rsschool-cv#4]
Добрый день! Вы проверяли мою работу — я её частично доделал, но не могу найти вас в дискорде :(

**Comment by IgorAblyak** [comment]
Петр, привет! Посмотрю еще раз, как смогу.

пт, 9 апр. 2021 г. в 17:09, Peter Kubasov ***@***.***>:

**Comment by kubasovp** [comment]
Спасибо. Тупо из-за работы не получилось сделать в полном объёме. А жаль, технически задание не сложное 🤷🏻‍♂️
